dist: trusty
sudo: required
before_script: test_helpers/install_nodejs4.sh
addons:
  firefox: "52.0"
matrix:
  include:

    - env: BUILD=emscripten-fastxpub
      script:
        - cd fastxpub && make clean && make docker-build && nvm install 8 && nvm use 8 && make test && cd ..
      services:
        - docker
      sudo: required
      install: true
      compiler: true
      node_js:
        - "8"

    - before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - test_helpers/install_nodejs4.sh
        - rm test/discovery.js test/bitcore.js
        - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
        - nvm install 8
      env: TEST_SUITE=unit TEST=build-tx
    - before_script:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - test_helpers/install_nodejs4.sh
        - mv karma.conf.js-buildtx karma.conf.js
      env: TEST_SUITE=karma-chrome TEST=build-tx
    - before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - test_helpers/install_nodejs4.sh
        - mv karma.conf.js-buildtx karma.conf.js
      env: TEST_SUITE=karma-firefox TEST=build-tx
      addons:
        firefox: latest

    - before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - test_helpers/install_nodejs4.sh
        - sudo test_helpers/install_regtest.sh
        - rm test/discovery.js test/build-tx.js
        - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
        - nvm install 8
      env: TEST_SUITE=unit TEST=bitcore
    - before_script:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - test_helpers/install_nodejs4.sh
        - sudo test_helpers/install_regtest.sh
        - mv karma.conf.js-bitcore karma.conf.js
      env: TEST_SUITE=karma-chrome TEST=bitcore
    - before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - test_helpers/install_nodejs4.sh
        - sudo test_helpers/install_regtest.sh
        - mv karma.conf.js-bitcore karma.conf.js
      env: TEST_SUITE=karma-firefox TEST=bitcore
      addons:
        firefox: latest

    - before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - test_helpers/install_nodejs4.sh
        - sudo test_helpers/install_regtest.sh
        - rm test/bitcore.js test/build-tx.js
        - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
        - nvm install 8
      env: TEST_SUITE=unit TEST=discovery
    - before_script:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - test_helpers/install_nodejs4.sh
        - sudo test_helpers/install_regtest.sh
        - mv karma.conf.js-discovery karma.conf.js
      env: TEST_SUITE=karma-chrome TEST=discovery
    - before_script:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - test_helpers/install_nodejs4.sh
        - sudo test_helpers/install_regtest.sh
        - mv karma.conf.js-discovery karma.conf.js
      env: TEST_SUITE=karma-firefox TEST=discovery
    - before_script:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - test_helpers/install_nodejs4.sh
        - sudo test_helpers/install_regtest.sh
        - mv karma.conf.js-discovery karma.conf.js
      addons:
        firefox: "50.0"
      env: TEST_SUITE=karma-firefox TEST=discovery-no-webasm

    - before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - test_helpers/install_nodejs4.sh
        - sudo test_helpers/install_regtest.sh
        - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.2/install.sh | bash
        - nvm install 8
      env: TEST_SUITE=coverage
env:
  - TEST_SUITE=eslint
  - TEST_SUITE=flow
  - TEST_SUITE=build-example
script: npm run-script $TEST_SUITE

notifications:
  webhooks:
    urls:
      - http://ci-bot.satoshilabs.com:5000/travis
    on_success: always
    on_failure: always
    on_start: always

