dist: trusty
sudo: required
before_script: test_helpers/install_nodejs8.sh
matrix:
  include:
    - before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - test_helpers/install_nodejs8.sh
        - sudo test_helpers/install_regtest.sh
        - rm test/discovery.js
      env: TEST_SUITE=unit TEST=bitcore
    - before_script:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - test_helpers/install_nodejs8.sh
        - sudo test_helpers/install_regtest.sh
        - mv karma.conf.js-bitcore karma.conf.js
      env: TEST_SUITE=karma-chrome TEST=bitcore
    - before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - test_helpers/install_nodejs8.sh
        - sudo test_helpers/install_regtest.sh
        - mv karma.conf.js-bitcore karma.conf.js
      env: TEST_SUITE=karma-firefox TEST=bitcore
      addons:
        firefox: latest

    - before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - test_helpers/install_nodejs8.sh
        - sudo test_helpers/install_regtest.sh
        - rm test/bitcore.js
      env: TEST_SUITE=unit TEST=discovery
    - before_script:
        - export CHROME_BIN=chromium-browser
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - test_helpers/install_nodejs8.sh
        - sudo test_helpers/install_regtest.sh
        - mv karma.conf.js-discovery karma.conf.js
      env: TEST_SUITE=karma-chrome TEST=discovery
    - before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - test_helpers/install_nodejs8.sh
        - sudo test_helpers/install_regtest.sh
        - mv karma.conf.js-discovery karma.conf.js
      env: TEST_SUITE=karma-firefox TEST=discovery
      addons:
        firefox: latest

    - before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
        - test_helpers/install_nodejs8.sh
        - sudo test_helpers/install_regtest.sh
      env: TEST_SUITE=coverage
env:
  - TEST_SUITE=eslint
  - TEST_SUITE=flow
  - TEST_SUITE=build-example
script: npm run-script $TEST_SUITE

notifications:
  webhooks:
    urls:
      - http://ci-bot.satoshilabs.com:5000/travis
    on_success: always
    on_failure: always
    on_start: always
